### ISSUE TITLE
Edisonfile for the console application

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Edison#39]
The `Edisonfile` will be of YAML format and will contain all the values that would normally be supplied on the command line. This file is only respected if `Edison.Console.exe` is run with no arguments, or the `--ef` argument is supplied to the location of the Edisonfile (or if it has a different name).

An example could be:

```yaml
assemblies:
  - "./some/path/test.dll"
  - "./some/other/test.dll"

output_type: "xml"
```

This will allow versioned arguments for Edison in a repository, for when more assemblies are added/removed or categories need to be excluded etc.
